added docs for multichain
Web3Auth/web3auth-docs pull request #181
Opened 2022-09-28 20:04 UTC by Saviour1001

2022-09-29 03:16 UTC, shahbaz17 requested changes
Please make the changes as discussed over the call.

2022-09-30 09:25 UTC, shahbaz17 requested changes

2022-09-30 09:25 UTC, shahbaz17 commented on docs/connect-blockchain/multi-chain.mdx
> +const { getED25519Key } = await import("@toruslabs/openlogin-ed25519");
@Saviour1001 please change this to use the function from `@web3auth/solana-provider` package.

2022-10-19 15:44 UTC, shahbaz17 commented
Hey @Saviour1001 

Can you please look at https://web3auth.io/docs/sdk/web/providers/solana#additional-reading? And check if this has any impact on this PR.

2022-10-20 15:18 UTC, Saviour1001 commented
Got it changed !

2022-10-20 15:59 UTC, shahbaz17 approved these changes
LGTM

2022-10-20 15:59 UTC, merged