Add Web3Auth Backend Docs
Web3Auth/web3auth-docs pull request #216
Opened 2022-11-03 08:41 UTC by shahbaz17

2022-11-04 13:34 UTC, yashovardhan requested changes
Apart from the comment I made, I feel this doc is incomplete due to the following reasons:
- This doesn't follow our structure of other SDK references. 
- We need additional page around custom authentication - I feel this doesn't support standard web3auth verifiers, only custom authentication is supported - please check about this.
- separate installation, initialisation, custom authentication and usage as 4 different pages
- we need to also add in the usage page why multi factor authentication doesn't work here, separate out

2022-11-04 13:34 UTC, yashovardhan commented on docs/sdk/web-backend.mdx
> +frontend SDKs. One thing to note here is that, with this you get semi-custodiality.
explain why this is semi custodial, maybe an architecture diagram will be a good addition. you can copy the one key flow diagram to edit the package name here. People need to know properly how this works.

2022-11-04 15:40 UTC, shahbaz17 commented
@yashovardhan 

Restructured the code and added more explanation on why this is needed.

2022-11-07 06:01 UTC, yashovardhan approved these changes
LGTM

2022-11-07 06:04 UTC, merged