Shifted Vite configs to different trouble shooting page
Web3Auth/web3auth-docs pull request #232
Opened 2022-11-22 19:05 UTC by Saviour1001

2022-11-26 04:45 UTC, shahbaz17 requested changes

2022-11-26 04:45 UTC, shahbaz17 commented on docs/troubleshooting/nodejs-polyfill-issues.mdx
> +description: "Webpack 5 Issues | Documentation - Web3Auth"
Update the description please

2022-12-06 03:00 UTC, yashovardhan commented on sidebars.js
>          "troubleshooting/jwt-errors",
rename the page as well

2022-12-15 02:31 UTC, yashovardhan commented
Hey @Saviour1001 please update this PR as discussed

2023-01-09 12:47 UTC, yashovardhan commented
@Saviour1001 please update this

2023-01-17 03:00 UTC, yashovardhan requested changes

2023-01-17 03:00 UTC, yashovardhan commented on docs/troubleshooting/bundler-polyfill-issues.mdx
> +The empty modal doesn't appear in production builds.
This should be in :::caution block

2023-01-17 15:36 UTC, yashovardhan approved these changes
LGTM

2023-01-17 15:36 UTC, merged