updated modal docs of custom auth
Web3Auth/web3auth-docs pull request #233
Opened 2022-11-24 17:30 UTC by Saviour1001

2022-11-26 04:43 UTC, shahbaz17 commented on docs/sdk/web/modal/custom-authentication.mdx
> +      jwt: {
This is wrong, there is no JWT with Modal.

2022-12-15 02:30 UTC, yashovardhan requested changes
Just update the common file for `CustomAuthenticationWeb3AuthExample` to use this.

2022-12-15 17:27 UTC, Saviour1001 commented
Done

2022-12-15 17:58 UTC, yashovardhan approved these changes
LGTM

2022-12-15 17:58 UTC, merged