Add Ripple provider
Web3Auth/web3auth-docs pull request #366
Opened 2023-04-26 06:40 UTC by shahbaz17

2023-05-18 11:11 UTC, develoQ reviewed
`XRPL` and `Ripple` are not identical.

It is appropriate to use `XRPL` here.
(`XRP` for currency).

XRP Ledger website is as follows
https://xrpl.org

2023-05-31 08:13 UTC, develoQ commented on docs/connect-blockchain/connect-blockchain.mdx
> +<TabItem value="ripple">
```suggestion
<TabItem value="XRPL">
```

2023-05-31 08:14 UTC, develoQ commented on docs/connect-blockchain/connect-blockchain.mdx
> +const rippleProvider = await web3auth.connect();
```suggestion
const xrplProvider = await web3auth.connect();
```

2023-05-31 08:14 UTC, develoQ commented on docs/connect-blockchain/connect-blockchain.mdx
> +- [Ripple Providers](/sdk/helper-sdks/providers/ripple)
```suggestion
- [XRPL Providers](/sdk/helper-sdks/providers/xrpl)
```

2023-05-31 08:14 UTC, develoQ commented on docs/connect-blockchain/ripple.mdx
> +image: "content-hub/guides/banners/ripple.png"
```suggestion
title: Integrate Web3Auth with the XRPL Blockchain
sidebar_label: XRPL
image: "content-hub/guides/banners/xrpl.png"
```

2023-05-31 08:15 UTC, develoQ commented on docs/connect-blockchain/ripple.mdx
> +description: "Integrate Web3Auth with the Ripple Blockchain | Documentation - Web3Auth"
```suggestion
description: "Integrate Web3Auth with the XRPL Blockchain | Documentation - Web3Auth"
```

2023-05-31 08:15 UTC, develoQ commented on docs/connect-blockchain/ripple.mdx
> +The Web3Auth Web SDK offers a standard provider for accessing the user's private key on non-EVM chains like [Ripple](https://ripple.com/). To enable a
```suggestion
The Web3Auth Web SDK offers a standard provider for accessing the user's private key on non-EVM chains like [XRPL](https://xrpl.org/). To enable a
```

2023-05-31 08:15 UTC, develoQ commented on docs/connect-blockchain/ripple.mdx
> +    provider: xrplProvider, // <-- Injecting the Ripple provider
```suggestion
    provider: xrplProvider, // <-- Injecting the XRPL provider
```

2023-05-31 08:16 UTC, develoQ commented on docs/connect-blockchain/ripple.mdx
> +const rippleProvider = await web3auth.connect(); // web3auth.provider
```suggestion
const xrplProvider = await web3auth.connect(); // web3auth.provider
```

2023-05-31 08:16 UTC, develoQ commented on docs/connect-blockchain/ripple.mdx
> +    const accInfo = (await rippleProvider.request({
```suggestion
    const accInfo = (await xrplProvider.request({
```

2023-05-31 08:17 UTC, develoQ commented on docs/connect-blockchain/ripple.mdx
> +      method: "ripple_signTransaction",
```suggestion
      method: "xrpl_signTransaction",
```

2023-05-31 08:19 UTC, develoQ commented on docs/connect-blockchain/ripple.mdx
> +      method: "ripple_submitTransaction",
```suggestion
      method: "xrpl_submitTransaction",
```

2023-05-31 08:20 UTC, develoQ commented on docs/connect-blockchain/ripple.mdx
> +---
The file name should be `xrpl.mdx`.

2023-05-31 08:20 UTC, develoQ commented on docs/sdk/helper-sdks/providers/ripple.mdx
> +---
The file name should be `xrpl.mdx`.

2023-05-31 08:20 UTC, develoQ commented on docs/sdk/helper-sdks/providers/ripple.mdx
> +description: "Ripple Provider | Documentation - Web3Auth"
```suggestion
title: XRPL Provider
displayed_sidebar: sdk
description: "XRPL Provider | Documentation - Web3Auth"
```

2023-05-31 08:21 UTC, develoQ commented on docs/sdk/helper-sdks/providers/ripple.mdx
> +#### `ripple_getAccounts`
```suggestion
#### `xrpl_getAccounts`
```

2023-05-31 08:22 UTC, develoQ commented on docs/sdk/helper-sdks/providers/ripple.mdx
> +  });
```suggestion
  // xrplProvider is from above
  const accounts = await xrplProvider.request<string[]>({
    method: "xrpl_getAccounts",
  });
```

2023-05-31 08:22 UTC, develoQ commented on docs/sdk/helper-sdks/providers/ripple.mdx
> +    const accInfo = (await rippleProvider.request({
```suggestion
    const accInfo = (await xrplProvider.request({
```

2023-05-31 08:22 UTC, develoQ commented on docs/sdk/helper-sdks/providers/ripple.mdx
> +#### `ripple_signTransaction`
```suggestion
#### `xrpl_signTransaction`
```

2023-05-31 08:23 UTC, develoQ commented on docs/sdk/helper-sdks/providers/ripple.mdx
> +      method: "ripple_signTransaction",
```suggestion
      method: "xrpl_signTransaction",
```

2023-05-31 08:23 UTC, develoQ commented on docs/sdk/helper-sdks/providers/ripple.mdx
> +#### `ripple_submitTransaction`
```suggestion
#### `xrpl_submitTransaction`
```

2023-05-31 08:23 UTC, develoQ commented on docs/sdk/helper-sdks/providers/ripple.mdx
> +      method: "ripple_submitTransaction",
```suggestion
      method: "xrpl_submitTransaction",
```

2023-05-31 08:23 UTC, develoQ commented on docs/sdk/helper-sdks/providers/ripple.mdx
> +#### `ripple_signMessage`
```suggestion
#### `xrpl_signMessage`
```

2023-05-31 08:24 UTC, develoQ commented on sidebars.js
> +        "connect-blockchain/ripple",
```suggestion
        "connect-blockchain/xrpl",
```

2023-05-31 08:24 UTC, develoQ commented on sidebars.js
> +        "sdk/helper-sdks/providers/ripple",
```suggestion
        "sdk/helper-sdks/providers/xrpl",
```

2023-05-31 08:24 UTC, develoQ commented on src/common/guides/_interacting-with-blockchain.mdx
> +- [Ripple Provider](/sdk/helper-sdks/providers/ripple) gives you the capability of making RPC calls to the Ripple blockchain.
```suggestion
- [XRPL Provider](/sdk/helper-sdks/providers/xrpl) gives you the capability of making RPC calls to the XRPL blockchain.
```

2023-05-31 08:25 UTC, develoQ commented on static/content-hub/guides/banners/ripple.png
The file name should be `xrpl.png`.

2023-05-31 08:27 UTC, develoQ commented on docs/sdk/helper-sdks/providers/ripple.mdx
> +const rippleProvider = await web3auth.connect();
```suggestion
const xrplProvider = await web3auth.connect();
```

2023-05-31 09:12 UTC, shahbaz17 commented
Hey @develoQ 

All reference of ripple is changes to xrpl

2023-05-31 09:15 UTC, develoQ requested changes
I see that there were a few items left, so I will request them!

Thank you for your kind!

2023-05-31 09:15 UTC, develoQ commented on docs/sdk/helper-sdks/providers/xrpl.mdx
> +#### `ripple_getAccounts`
```suggestion
#### `xrpl_getAccounts`
```

2023-05-31 09:15 UTC, develoQ commented on docs/sdk/helper-sdks/providers/xrpl.mdx
> +      method: "ripple_signTransaction",
```suggestion
      method: "xrpl_signTransaction",
```

2023-05-31 09:15 UTC, develoQ commented on docs/sdk/helper-sdks/providers/xrpl.mdx
> +      method: "ripple_submitTransaction",
```suggestion
      method: "xrpl_submitTransaction",
```

2023-05-31 09:28 UTC, develoQ approved these changes
Thank you for your time!

2023-06-07 10:56 UTC, merged