[v8] Update docs
Web3Auth/web3auth-docs pull request #608
Opened 2024-02-09 02:41 UTC by AyushBherwani1998

2024-02-13 12:06 UTC, ihsraham requested changes
Please update the usage section for modal SDK as well. You can take a reference from my PR for no modal SDK [here](https://github.com/Web3Auth/web3auth-docs/blob/no-modal-v8-docs/docs/sdk/pnp/web/no-modal/usage.mdx#L163-L164).

2024-02-13 17:14 UTC, AyushBherwani1998 commented
> Please update the usage section for modal SDK as well. You can take a reference from my PR for no modal SDK [here](https://github.com/Web3Auth/web3auth-docs/blob/no-modal-v8-docs/docs/sdk/pnp/web/no-modal/usage.mdx#L163-L164).

I checked your PR, let's keep it inside common like other methods. This way we'll have to maintain in a single place. If you can move it inside common, I'll take it from there. Let me know if it makes sense? I have updated the docs tho by adding the definition and description.

2024-02-14 02:15 UTC, ihsraham reviewed
Some more minor formatting stuff to look into.

2024-02-23 18:39 UTC, yashovardhan approved these changes

2024-02-23 18:39 UTC, merged