Add microsoft ouath2 guide
Web3Auth/web3auth-docs pull request #642
Opened 2024-03-04 13:28 UTC by rtomas

No image for the header yet.

2024-03-04 13:45 UTC, rtomas commented
link to the guide: https://web3auth-docs-git-add-microsoft-ouath2-guide-web3auth.vercel.app/guides/microsoft-oauth

2024-03-04 20:49 UTC, shahbaz17 commented on src/pages/guides/microsoft-oauth.mdx
> +image: "content-hub/guides/banners/"
Use the image I sent you over DM here. Also on Auth Provider page of Microsoft

2024-03-04 20:52 UTC, shahbaz17 requested changes
Overall looks good to me.

Please resolve the comments and then this is good to merge.

2024-03-04 20:52 UTC, shahbaz17 commented on src/pages/guides/microsoft-oauth.mdx
> +image: "content-hub/guides/banners/"
Use the image I sent you over DM here. Also on Auth Provider page of Microsoft

2024-03-04 20:52 UTC, shahbaz17 commented on src/pages/guides/microsoft-oauth.mdx
> +order: 1
Please, make it like 3 or 4, so we have the current pinned one at the top.

2024-03-04 20:52 UTC, shahbaz17 commented on src/pages/guides/microsoft-oauth.mdx
> +  image="https://web3auth.io/docs/content-hub/guides/banners/"
Add image here too.

2024-03-04 20:54 UTC, shahbaz17 commented on src/pages/guides/microsoft-oauth.mdx
> +Repository: https://github.com/rtomas/microsoft-oauth-for-web3auth
Also, let's bring this inside, `web3auth-pnp-examples` for now.

2024-03-05 04:29 UTC, shahbaz17 approved these changes
lgtm

2024-03-05 13:23 UTC, merged