Add guide multiple chains
Web3Auth/web3auth-docs pull request #654
Opened 2024-03-13 15:16 UTC by rtomas

- Add guide for multiple chain connection
- Fix a link in Microsoft Oauth Guide

- The example must be approve: https://github.com/Web3Auth/web3auth-pnp-examples/pull/855

2024-04-19 05:48 UTC, shahbaz17 requested changes

2024-04-19 05:48 UTC, shahbaz17 commented on src/pages/guides/pnp-no-modal-multichain.mdx
> +order: 1
Please change the order for this guide, not sure we want this as our first guide. Also, change the guide order based on the date, and have a featured boolean label to display some guides as required.

2024-05-15 03:20 UTC, shahbaz17 requested changes
Left some comments on the preview. Please check once @rtomas

2024-06-04 02:53 UTC, shahbaz17 commented
> * Add guide for multiple chain connection
> * First, we have to merge (because of dependencies) : [[Guide] Build a MPC wallet in iOS #702](https://github.com/Web3Auth/web3auth-docs/pull/702) and then update this PR
> 
> https://web3auth-docs-git-add-guide-multiple-chains-web3auth.vercel.app/guides/pnp-no-modal-multichain

Why this is a dependency @rtomas ?

2024-06-06 01:06 UTC, rtomas commented
> > * Add guide for multiple chain connection
> > * First, we have to merge (because of dependencies) : [[Guide] Build a MPC wallet in iOS #702](https://github.com/Web3Auth/web3auth-docs/pull/702) and then update this PR
> > 
> > https://web3auth-docs-git-add-guide-multiple-chains-web3auth.vercel.app/guides/pnp-no-modal-multichain
> 
> Why this is a dependency @rtomas ?

There is no need to approve that dependency

2024-06-06 04:20 UTC, shahbaz17 approved these changes
lgtm

2024-06-06 04:20 UTC, merged