Improve sorting logic in Guides component
Web3Auth/web3auth-docs pull request #680
Opened 2024-04-01 18:39 UTC by rtomas

+ order by Date
+ Possibility to add pinned: 1 to show it first

2024-04-03 13:20 UTC, yashovardhan requested changes
1. `pinned` should be a boolean
2. remove order from all the guides

2024-04-03 18:18 UTC, rtomas commented
> * `pinned` should be a boolean
> * remove order from all the guides

fixed 
cc: @yashovardhan

2024-04-04 03:46 UTC, yashovardhan approved these changes

2024-04-09 12:05 UTC, yashovardhan approved these changes

2024-04-09 12:05 UTC, merged