doc: CustomChainConfig blockExplorer -> blockExplorerUrl
Web3Auth/web3auth-docs pull request #685
Opened 2024-04-04 15:23 UTC by Taewa

If I understand correctly, `CustomChainConfig` 's `blockExplorer` no longer exists but `blockExplorerUrl` as an optional.
So I updated all related document.

CustomChainConfig : https://github.com/Web3Auth/web3auth-web/blob/master/packages/base/src/chain/IChainInterface.ts

2024-04-08 08:37 UTC, Taewa commented
Hi @shahbaz17 
Do I have to assign anyone in order to kick start the PR? Or just wait to be reviewed?

2024-04-09 10:45 UTC, Taewa commented
Hi @rtomas 
I wonder if I need some additional steps to request PR?

2024-04-19 04:26 UTC, ihsraham requested changes

2024-04-19 04:26 UTC, ihsraham commented on docs/sdk/core-kit/sfa-react-native/usage.mdx
> +  blockExplorerUrl?: string;
Hey @Taewa,
Great job with the PR, and thanks for your contribution. But the SFA React native SDK hasn't been updated to use the updated ChainConfig. Once it's done, feel free to raise a PR again. For now, switch this back to blockExplorer. Make these changes and I'll be glad to merge your PR and mark your first contribution here. Thanks!

2024-05-02 16:45 UTC, avious00 commented
hey @ihsraham the footer docs links are broken too: 
under Product
[Plug & Play](https://web3auth.io/docs/pnp/introduction)
[Core Kit](https://web3auth.io/docs/core-kit/introduction) 

it's going to the old /sdk/pnp/ path but the new url is https://web3auth.io/docs/examples?product=Plug+and+Play

2024-06-11 10:25 UTC, closed without merging